---
# handlers file for common
- name: update-ca-trust
  become: yes
  command: update-ca-certificates

- name: restart docker
  become: yes
  service:
    name: docker
    state: restarted

- include: supervisord.yml