---
- name: ensure customized bin
  become: yes
  file:
    path: "{{ customized_bin_dir }}"
    state: directory
  tags:
    - common

- name: setup cadvisor supervisord config
  become: yes
  template:
    src: cadvisor_supervisord.conf.j2
    dest: "{{ supervisord_conf_dir }}/cadvisor_supervisord.conf"
  notify: reload supervisord
  tags:
    - common

- name: setup cadvisor start up script
  become: yes
  template: 
    src: start_cadvisor.sh.j2 
    dest: "{{ customized_bin_dir }}/start_cadvisor.sh"
    mode: 0755
  notify: reload supervisord
  tags:
    - common