---
- name: install latest docker
  become: yes
  shell: "curl -sSL https://get.docker.com/ | sh"
  tags:
    - bootstrap
    - docker

- name: update docker default settings
  become: yes
  template:
    src: default_docker.j2
    dest: /etc/default/docker
  notify:
    - restart docker
  tags:
    - docker
    - bootstrap

- name: ensure consul config dir
  become: yes
  file: 
    path: /etc/consul.d 
    state: directory
  tags:
    - docker
    - bootstrap

- name: setup consul service check
  become: yes
  copy:
    src: docker_service.json
    dest: /etc/consul.d/docker_service.json
  tags:
    - docker
    - bootstrap

- name: create directory for systemd drop-ins
  become: yes
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755
  tags:
    - docker

- name: systemd drop-in for options
  sudo: yes
  template:
    src:  "{{ item }}.j2"
    dest: "/etc/systemd/system/docker.service.d/{{ item }}"
  with_items:
    - 10-options.conf
    - 12-network-options.conf
  notify:
    - reload docker
  tags:
    - docker

- name: systemd drop-in for ExecStart
  sudo: yes
  copy:
    src: 20-ExecStart.conf.j2
    dest: /etc/systemd/system/docker.service.d/20-ExecStart.conf
  notify:
    - reload docker
  tags:
    - docker

