---
- name: ensure cloud init config dir
  become: yes
  file: 
    path: /etc/cloud/cloud.cfg.d
    state: directory
  tags:
    - common

- name: preserve hostname
  become: yes
  copy:
    src: 02_hostname.cfg
    dest: /etc/cloud/cloud.cfg.d/02_hostname.cfg
    owner: root
    group: root
    mode: 0644
  when: provider in cloud_init_providers
  tags:
    - common

- name: set persistent hostname
  become: yes
  copy:
    dest: /etc/hostname
    content: "{{ inventory_hostname }}"
    force: yes
    owner: root
    group: root
    mode: 0644
  tags:
  - common
