- name: disable requiretty in sudoers
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: ^.+requiretty$
    line: "# Defaults requiretty"
  tags:
  - common

- include: pkg_install.yml
  when: ansible_os_family == 'RedHat'

- include: pkg_install_debian.yml
  when: ansible_os_family == 'Debian'

- include: ulimit.yml

- include: rc_local.yml

- include: ssl.yml

- include: users.yml

- include: ssh.yml

- include: hostname.yml

# install docker and supervisord

- include: docker.yml

# install additional services and reload supervisord
# install netdata directly on the host machine
- include: adds_on.yml
