---
- name: develop tools
  become: yes
  yum: name="@Development tools" state=present

- name: install system pkgs
  become: yes
  yum: "name={{ item }} state=present"
  with_items: system_pkgs