---
- name: setup fluentd agent supervisord config
  become: yes
  template:
    src: traefik_fluentd_agent_supervisord.conf.j2
    dest: "{{ supervisord_conf_dir }}/fluentd_agent.conf"
  notify:
    - reload supervisord 
    - restart fluentd agent
  tags:
    - traefik

- name: setup fluentd agent start up script
  become: yes
  template:
    src: start_fluentd_agent.sh.j2
    dest: "/opt/bin/start_fluentd_agent.sh"
    mode: 0755
  notify: reload supervisord
  tags:
    - traefik

- name: ensure fluentd config directory
  become: yes
  file:
    path: "/etc/fluentd"
    state: directory
  tags:
    - traefik

- name: setup fluentd agent config
  become: yes
  template:
    src: fluentd_agent.conf.j2
    dest: "/etc/fluentd/fluentd_agent.conf"
  notify: restart fluentd agent
  tags:
    - traefik

- name: setup consul service check fluentd_agent
  become: yes
  copy:
    src: fluentd_agent_service.json
    dest: /etc/consul.d/fluentd_agent_service.json
  notify: reload consul config
  tags:
    - traefik